---
version: '3'

services:
  influxdb:
    image: influxdb:2.0.8-alpine
    container_name: influxdb
    volumes:
    - influxdb:/var/lib/influxdb2
    ports: 
    - 8086:8086
    environment:
    - DOCKER_INFLUXDB_INIT_MODE=setup
    - DOCKER_INFLUXDB_INIT_USERNAME=admin
    - DOCKER_INFLUXDB_INIT_PASSWORD=password
    - DOCKER_INFLUXDB_INIT_ORG=covid-19
    - DOCKER_INFLUXDB_INIT_BUCKET=covid-data
    networks:
    - internal
  grafana:
    image: grafana/grafana:8.1.2-ubuntu
    container_name: grafana
    ports:
    - 3000:3000
    networks:
    - internal
    depends_on:
    - influxdb


volumes:
  influxdb: {}

networks:
  internal: {}