---
apiVersion: 1

datasources:
  - name: influxdb-Flux
    type: influxdb
    isDefault: true
    access: proxy
    url: ${INFLUXDB_URL}
    timeout: 120
    basicAuth: true
    basicAuthUser: ${INFLUXDB_USER}
    jsonData:
      defaultBucket: ${INFLUXDB_DEFAULT_BUCKET}
      httpMode: GET
      organization: ${INFLUXDB_ORG}
      version: Flux
    secureJsonData:
      basicAuthPassword: ${INFLUXDB_PASSWORD}
      token: ${INFLUXDB_TOKEN}
    version: 1
    editable: false
